export let randomFoods = [
    {"meals": [
    {
        "idMeal": "52992",
        "strMeal": "Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots",
        "strDrinkAlternate": null,
        "strCategory": "Beef",
        "strArea": "American",
        "strInstructions": "1. Preheat oven to 425 degrees. Wash and dry all produce. Dice potatoes into 1/2-inch pieces. Trim, peel, and cut carrots on a diagonal into 1/2-inch-thick pieces. Trim and thinly slice scallions, separating whites from greens; finely chop whites. Peel and finely chop garlic.\r\n\r\n2. In a medium bowl, soak bread with 2 TBSP water (4 TBSP for 4 servings); break up with your hands until pasty. Stir in beef, sriracha, scallion whites, half the garlic, salt (we used 3/4 tsp kosher salt; 11/2 tsp for 4), and pepper. Form into two 1-inch-tall loaves (four loaves for 4). Place on one side of a baking sheet. Toss carrots on empty side of same sheet with a drizzle of oil, salt, and pepper. (For 4, spread meatloaves out across whole sheet and add carrots to a second sheet.) Bake for 20 minutes (we'll glaze the meatloaves then).\r\n\r\n3. Meanwhile, place potatoes in a medium pot with enough salted water to cover by 2 inches. Bring to a boil and cook until very\r\ntender, 12-15 minutes. Reserve 1/2 cup potato cooking liquid, then drain. While potatoes cook, in a small bowl, combine soy sauce, garlic powder, 1/4 cup ketchup (1/2 cup for 4 servings), and 2 tsp sugar (4 tsp for 4).\r\n\r\n4. Once meatloaves and carrots have baked 20 minutes, remove from oven. Spoon half the ketchup glaze over meatloaves (save\r\nthe rest for serving); return to oven until carrots are browned and tender, meatloaves are cooked through, and glaze is tacky, 4-5 minutes more.\r\n\r\n5. Meanwhile, melt 2 TBSP butter (4 TBSP for 4 servings) in pot used for potatoes over medium heat. Add remaining garlic and cook\r\nuntil fragrant, 30 seconds. Add potatoes and 1/4 tsp wasabi. Mash, adding splashes of reserved potato cooking liquid as necessary until smooth. Season with salt and pepper. (If you like things spicy, stir in more wasabi!)\r\n\r\n6. Divide meatloaves, mashed potatoes, and roasted carrots between plates. Sprinkle with scallion greens and serve with remaining ketchup glaze on the side for dipping.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/o2wb6p1581005243.jpg",
        "strTags": null,
        "strYoutube": "",
        "strIngredient1": "Potatoes",
        "strIngredient2": "Carrots",
        "strIngredient3": "Scallions",
        "strIngredient4": "Garlic",
        "strIngredient5": "Bread",
        "strIngredient6": "Garlic Powder",
        "strIngredient7": "Soy Sauce",
        "strIngredient8": "Ground Beef",
        "strIngredient9": "Vegetable Oil",
        "strIngredient10": "Sugar",
        "strIngredient11": "Butter",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "5",
        "strMeasure2": "12 ounces",
        "strMeasure3": "1",
        "strMeasure4": "2 cloves",
        "strMeasure5": "1 Slice",
        "strMeasure6": "1",
        "strMeasure7": "2",
        "strMeasure8": "1",
        "strMeasure9": "1 tsp ",
        "strMeasure10": "2 tsp",
        "strMeasure11": "2 tbsp",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "52782",
        "strMeal": "Lamb tomato and sweet spices",
        "strDrinkAlternate": null,
        "strCategory": "Lamb",
        "strArea": "Moroccan",
        "strInstructions": "Use pickled vine leaves here, preserved in brine. Small delicate leaves are better than the large bristly ones but, if only large leaves are to hand, then trim them to roughly 12 by 12 cms so that you don't get too many layers of leaves around the filling. And remove any stalks. Drain the preserved leaves, immerse them in boiling water for 10 minutes and then leave to dry on a tea towel before use. \r\nBasmati rice with butter and pine nuts is an ideal accompaniment. Couscous is great, too. Serves four.\r\nFirst make the filling. Put all the ingredients, apart from the tomatoes, in a bowl. Cut the tomatoes in half, coarsely grate into the bowl and discard the skins. Add half a teaspoon of salt and some black pepper, and stir. Leave on the side, or in the fridge, for up to a day. Before using, gently squeeze with your hands and drain away any juices that come out.\r\nTo make the sauce, heat the oil in a medium pan. Add the ginger and garlic, cook for a minute or two, taking care not to burn them, then add the tomato, lemon juice and sugar. Season, and simmer for 20 minutes.\r\nWhile the sauce is bubbling away, prepare the vine leaves. Use any torn or broken leaves to line the base of a wide, heavy saucepan. Trim any leaves from the fennel, cut it vertically into 0.5cm-thick slices and spread over the base of the pan to cover completely.\r\nLay a prepared vine leaf (see intro) on a work surface, veiny side up. Put two teaspoons of filling at the base of the leaf in a 2cm-long by 1cm-wide strip. Fold the sides of the leaf over the filling, then roll it tightly from bottom to top, in a cigar shape. Place in the pan, seam down, and repeat with the remaining leaves, placing them tightly next to each other in lines or circles (in two layers if necessary).\r\nPour the sauce over the leaves (and, if needed, add water just to cover). Place a plate on top, to weigh the leaves down, then cover with a lid. Bring to a boil, reduce the heat and cook on a bare simmer for 70 minutes. Most of the liquid should evaporate. Remove from the heat, and leave to cool a little - they are best served warm. When serving, bring to the table in the pan - it looks great. Serve a few vine leaves and fennel slices with warm rice. Spoon the braising juices on top and garnish with coriander.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qtwtss1468572261.jpg",
        "strTags": "",
        "strYoutube": "https://www.youtube.com/watch?v=vaZb1MnFBgA",
        "strIngredient1": "olive oil",
        "strIngredient2": "ginger",
        "strIngredient3": "garlic",
        "strIngredient4": "tomatoes",
        "strIngredient5": "lemon juice",
        "strIngredient6": "caster sugar",
        "strIngredient7": "vine leaves",
        "strIngredient8": "fennel bulb",
        "strIngredient9": "lamb mince",
        "strIngredient10": "onion",
        "strIngredient11": "potato",
        "strIngredient12": "basmati rice",
        "strIngredient13": "chopped parsley",
        "strIngredient14": "coriander",
        "strIngredient15": "lemon juice",
        "strIngredient16": "garlic",
        "strIngredient17": "clove",
        "strIngredient18": "cinnamon",
        "strIngredient19": "tomatoes",
        "strIngredient20": "",
        "strMeasure1": "2 tbsp",
        "strMeasure2": "4cm piece finely chopped",
        "strMeasure3": "2 cloves peeled and chopped",
        "strMeasure4": "800g peeled and chopped ",
        "strMeasure5": "2 tbsp",
        "strMeasure6": "1 tsp",
        "strMeasure7": "50",
        "strMeasure8": "1 large",
        "strMeasure9": "400g",
        "strMeasure10": "1 medium",
        "strMeasure11": "1 small peeled and coarsely grated",
        "strMeasure12": "2 tbsp",
        "strMeasure13": "2 tbsp",
        "strMeasure14": "2 tbsp chopped",
        "strMeasure15": "1 tbsp",
        "strMeasure16": "2 cloves",
        "strMeasure17": "½ tsp ground",
        "strMeasure18": "½ tsp ground ",
        "strMeasure19": "2 medium",
        "strMeasure20": "",
        "strSource": "http://www.ottolenghi.co.uk/recipes/meat/lamb-tomato-and-sweet-spices-shop",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "52792",
        "strMeal": "Bread and Butter Pudding",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Grease a 1 litre/2 pint pie dish with butter.\r\nCut the crusts off the bread. Spread each slice with on one side with butter, then cut into triangles.\r\nArrange a layer of bread, buttered-side up, in the bottom of the dish, then add a layer of sultanas. Sprinkle with a little cinnamon, then repeat the layers of bread and sultanas, sprinkling with cinnamon, until you have used up all of the bread. Finish with a layer of bread, then set aside.\r\nGently warm the milk and cream in a pan over a low heat to scalding point. Don't let it boil.\r\nCrack the eggs into a bowl, add three quarters of the sugar and lightly whisk until pale.\r\nAdd the warm milk and cream mixture and stir well, then strain the custard into a bowl.\r\nPour the custard over the prepared bread layers and sprinkle with nutmeg and the remaining sugar and leave to stand for 30 minutes.\r\nPreheat the oven to 180C/355F/Gas 4.\r\nPlace the dish into the oven and bake for 30-40 minutes, or until the custard has set and the top is golden-brown.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/xqwwpy1483908697.jpg",
        "strTags": "Pudding,Brunch",
        "strYoutube": "https://www.youtube.com/watch?v=Vz5W1-BmOE4",
        "strIngredient1": "butter",
        "strIngredient2": "bread",
        "strIngredient3": "sultanas",
        "strIngredient4": "cinnamon",
        "strIngredient5": "milk",
        "strIngredient6": "double cream",
        "strIngredient7": "eggs",
        "strIngredient8": "sugar",
        "strIngredient9": "nutmeg",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "25g/1oz",
        "strMeasure2": "8 thin slices",
        "strMeasure3": "50g/2oz",
        "strMeasure4": "2 tsp",
        "strMeasure5": "350ml/12fl",
        "strMeasure6": "50ml/2fl oz",
        "strMeasure7": "2 free-range",
        "strMeasure8": "25g/1oz",
        "strMeasure9": "grated, to taste",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://cooking.nytimes.com/recipes/1018529-coq-au-vin",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "52959",
        "strMeal": "Baked salmon with fennel & tomatoes",
        "strDrinkAlternate": null,
        "strCategory": "Seafood",
        "strArea": "British",
        "strInstructions": "Heat oven to 180C/fan 160C/gas 4. Trim the fronds from the fennel and set aside. Cut the fennel bulbs in half, then cut each half into 3 wedges. Cook in boiling salted water for 10 mins, then drain well. Chop the fennel fronds roughly, then mix with the parsley and lemon zest.\r\n\r\nSpread the drained fennel over a shallow ovenproof dish, then add the tomatoes. Drizzle with olive oil, then bake for 10 mins. Nestle the salmon among the veg, sprinkle with lemon juice, then bake 15 mins more until the fish is just cooked. Scatter over the parsley and serve.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/1548772327.jpg",
        "strTags": "Paleo,Keto,HighFat,Baking,LowCarbs",
        "strYoutube": "https://www.youtube.com/watch?v=xvPR2Tfw5k0",
        "strIngredient1": "Fennel",
        "strIngredient2": "Parsley",
        "strIngredient3": "Lemon",
        "strIngredient4": "Cherry Tomatoes",
        "strIngredient5": "Olive Oil",
        "strIngredient6": "Salmon",
        "strIngredient7": "Black Olives",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "2 medium",
        "strMeasure2": "2 tbs chopped",
        "strMeasure3": "Juice of 1",
        "strMeasure4": "175g",
        "strMeasure5": "1 tbs",
        "strMeasure6": "350g",
        "strMeasure7": "to serve",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/7745/baked-salmon-with-fennel-and-tomatoes",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }
]}]